name: Build Find Duplicate File EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # 打包为 EXE
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name calculated_value calculated_value.py

    # 将打包的文件保存到 GitHub Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: calculated_value
        path: dist/calculated_value.exe
