name: Build 图片调整打孔处理小工具 for Windows

on:
  push:
    branches:
      - main  # 在 main 分支推送代码时触发构建

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # 使用最新版本的 checkout 动作

    - name: Setup Python
      uses: actions/setup-python@v4  # 使用最新版本的 setup-python 动作
      with:
        python-version: 3.9  # 指定 Python 版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_update_image_size.txt
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed 图片尺寸调整打孔小工具.py
    - name: Upload EXE
      uses: actions/upload-artifact@v4  # 更新为 v4 版本
      with:
        name: Image-punching-processing
        path: dist/Image-punching-processing.exe
