name: Build 油田电子表数据处理 for Windows

on:
  push:
    branches:
      - main  # 在 main 分支推送代码时触发构建

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # 使用最新版本的 checkout 动作

    - name: Setup Python
      uses: actions/setup-python@v4  # 使用最新版本的 setup-python 动作
      with:
        python-version: 3.9  # 指定 Python 版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_youtian_excel.txt
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed youtian_excel.py
    - name: Upload EXE
      uses: actions/upload-artifact@v3  # 更新为 v3 版本
      with:
        name: youtian_excel-exe
        path: dist/youtian_excel.exe
